// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/crm" | "/admin/guvenlik" | "/admin/kullanicilar" | "/admin/link-havuzu" | "/admin/ogrenme-merkezi" | "/admin/poi-onay" | "/admin/radar" | "/admin/radar/analitik" | "/admin/sistem-ayarlari" | "/araclarim" | "/auth/reset" | "/giris" | "/hakkimizda" | "/ilan-ver" | "/ilan/[id]" | "/ilan/[id]/sahiplen" | "/kullanim-kosullari" | "/kvkk" | "/moderator" | "/moderator-giris" | "/nasil-calisir" | "/panel" | "/profil-tamamla" | "/u/[username]" | "/yol-rehberi"
type AppRouteHandlerRoutes = "/api/admin/crm" | "/api/admin/crm/[id]" | "/api/admin/crm/[id]/analiz" | "/api/admin/enrich-poi" | "/api/admin/guvenlik" | "/api/admin/kullanici" | "/api/admin/learn-aliases" | "/api/admin/link-havuzu" | "/api/admin/poi" | "/api/admin/poi-import" | "/api/admin/poi-import/[id]/summarize" | "/api/admin/radar" | "/api/admin/radar/analitik" | "/api/admin/reprocess-no-lane" | "/api/admin/resolve-url" | "/api/auth/dogrulama-tekrar" | "/api/auth/giris" | "/api/auth/log" | "/api/auth/merge" | "/api/auth/otp" | "/api/auth/switch-account" | "/api/auth/tekil-kontrol" | "/api/excel-import" | "/api/ilan/[id]/sahiplen" | "/api/ilan/[id]/telefon" | "/api/ilan/duzelt" | "/api/ilan/pasif" | "/api/ilan/sil" | "/api/ilanlar/[id]" | "/api/listings/ara" | "/api/listings/yakin" | "/api/llm-parse" | "/api/moderator/arsiv" | "/api/moderator/kullanici-askiya" | "/api/moderator/toplu-islem" | "/api/parse-text" | "/api/poi" | "/api/poi/[id]" | "/api/poi/[id]/review" | "/api/raw-posts/telefon-doldur" | "/api/whatsapp" | "/api/whatsapp-parse" | "/auth/callback" | "/auth/devir" | "/cikis"
type PageRoutes = never
type LayoutRoutes = "/" | "/auth" | "/giris" | "/moderator-giris" | "/profil-tamamla"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/crm": {}
  "/admin/guvenlik": {}
  "/admin/kullanicilar": {}
  "/admin/link-havuzu": {}
  "/admin/ogrenme-merkezi": {}
  "/admin/poi-onay": {}
  "/admin/radar": {}
  "/admin/radar/analitik": {}
  "/admin/sistem-ayarlari": {}
  "/api/admin/crm": {}
  "/api/admin/crm/[id]": { "id": string; }
  "/api/admin/crm/[id]/analiz": { "id": string; }
  "/api/admin/enrich-poi": {}
  "/api/admin/guvenlik": {}
  "/api/admin/kullanici": {}
  "/api/admin/learn-aliases": {}
  "/api/admin/link-havuzu": {}
  "/api/admin/poi": {}
  "/api/admin/poi-import": {}
  "/api/admin/poi-import/[id]/summarize": { "id": string; }
  "/api/admin/radar": {}
  "/api/admin/radar/analitik": {}
  "/api/admin/reprocess-no-lane": {}
  "/api/admin/resolve-url": {}
  "/api/auth/dogrulama-tekrar": {}
  "/api/auth/giris": {}
  "/api/auth/log": {}
  "/api/auth/merge": {}
  "/api/auth/otp": {}
  "/api/auth/switch-account": {}
  "/api/auth/tekil-kontrol": {}
  "/api/excel-import": {}
  "/api/ilan/[id]/sahiplen": { "id": string; }
  "/api/ilan/[id]/telefon": { "id": string; }
  "/api/ilan/duzelt": {}
  "/api/ilan/pasif": {}
  "/api/ilan/sil": {}
  "/api/ilanlar/[id]": { "id": string; }
  "/api/listings/ara": {}
  "/api/listings/yakin": {}
  "/api/llm-parse": {}
  "/api/moderator/arsiv": {}
  "/api/moderator/kullanici-askiya": {}
  "/api/moderator/toplu-islem": {}
  "/api/parse-text": {}
  "/api/poi": {}
  "/api/poi/[id]": { "id": string; }
  "/api/poi/[id]/review": { "id": string; }
  "/api/raw-posts/telefon-doldur": {}
  "/api/whatsapp": {}
  "/api/whatsapp-parse": {}
  "/araclarim": {}
  "/auth": {}
  "/auth/callback": {}
  "/auth/devir": {}
  "/auth/reset": {}
  "/cikis": {}
  "/giris": {}
  "/hakkimizda": {}
  "/ilan-ver": {}
  "/ilan/[id]": { "id": string; }
  "/ilan/[id]/sahiplen": { "id": string; }
  "/kullanim-kosullari": {}
  "/kvkk": {}
  "/moderator": {}
  "/moderator-giris": {}
  "/nasil-calisir": {}
  "/panel": {}
  "/profil-tamamla": {}
  "/u/[username]": { "username": string; }
  "/yol-rehberi": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/auth": never
  "/giris": never
  "/moderator-giris": never
  "/profil-tamamla": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
