// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm">> = Specific
  const handler = {} as typeof import("../../app/admin/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/guvenlik/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/guvenlik">> = Specific
  const handler = {} as typeof import("../../app/admin/guvenlik/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/kullanicilar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kullanicilar">> = Specific
  const handler = {} as typeof import("../../app/admin/kullanicilar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/link-havuzu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/link-havuzu">> = Specific
  const handler = {} as typeof import("../../app/admin/link-havuzu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ogrenme-merkezi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ogrenme-merkezi">> = Specific
  const handler = {} as typeof import("../../app/admin/ogrenme-merkezi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/poi-onay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/poi-onay">> = Specific
  const handler = {} as typeof import("../../app/admin/poi-onay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/radar/analitik/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/radar/analitik">> = Specific
  const handler = {} as typeof import("../../app/admin/radar/analitik/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/radar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/radar">> = Specific
  const handler = {} as typeof import("../../app/admin/radar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sistem-ayarlari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sistem-ayarlari">> = Specific
  const handler = {} as typeof import("../../app/admin/sistem-ayarlari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/araclarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/araclarim">> = Specific
  const handler = {} as typeof import("../../app/araclarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset">> = Specific
  const handler = {} as typeof import("../../app/auth/reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/giris/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/giris">> = Specific
  const handler = {} as typeof import("../../app/giris/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hakkimizda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hakkimizda">> = Specific
  const handler = {} as typeof import("../../app/hakkimizda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ilan-ver/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ilan-ver">> = Specific
  const handler = {} as typeof import("../../app/ilan-ver/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ilan/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ilan/[id]">> = Specific
  const handler = {} as typeof import("../../app/ilan/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ilan/[id]/sahiplen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ilan/[id]/sahiplen">> = Specific
  const handler = {} as typeof import("../../app/ilan/[id]/sahiplen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kullanim-kosullari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kullanim-kosullari">> = Specific
  const handler = {} as typeof import("../../app/kullanim-kosullari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kvkk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kvkk">> = Specific
  const handler = {} as typeof import("../../app/kvkk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/moderator-giris/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/moderator-giris">> = Specific
  const handler = {} as typeof import("../../app/moderator-giris/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/moderator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/moderator">> = Specific
  const handler = {} as typeof import("../../app/moderator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/nasil-calisir/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nasil-calisir">> = Specific
  const handler = {} as typeof import("../../app/nasil-calisir/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/panel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel">> = Specific
  const handler = {} as typeof import("../../app/panel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profil-tamamla/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profil-tamamla">> = Specific
  const handler = {} as typeof import("../../app/profil-tamamla/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../app/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/yol-rehberi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yol-rehberi">> = Specific
  const handler = {} as typeof import("../../app/yol-rehberi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/crm/[id]/analiz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/crm/[id]/analiz">> = Specific
  const handler = {} as typeof import("../../app/api/admin/crm/[id]/analiz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/crm/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/crm/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/crm/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/crm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/crm">> = Specific
  const handler = {} as typeof import("../../app/api/admin/crm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/enrich-poi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/enrich-poi">> = Specific
  const handler = {} as typeof import("../../app/api/admin/enrich-poi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/guvenlik/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/guvenlik">> = Specific
  const handler = {} as typeof import("../../app/api/admin/guvenlik/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/kullanici/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/kullanici">> = Specific
  const handler = {} as typeof import("../../app/api/admin/kullanici/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/learn-aliases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/learn-aliases">> = Specific
  const handler = {} as typeof import("../../app/api/admin/learn-aliases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/link-havuzu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/link-havuzu">> = Specific
  const handler = {} as typeof import("../../app/api/admin/link-havuzu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/poi-import/[id]/summarize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/poi-import/[id]/summarize">> = Specific
  const handler = {} as typeof import("../../app/api/admin/poi-import/[id]/summarize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/poi-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/poi-import">> = Specific
  const handler = {} as typeof import("../../app/api/admin/poi-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/poi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/poi">> = Specific
  const handler = {} as typeof import("../../app/api/admin/poi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/radar/analitik/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/radar/analitik">> = Specific
  const handler = {} as typeof import("../../app/api/admin/radar/analitik/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/radar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/radar">> = Specific
  const handler = {} as typeof import("../../app/api/admin/radar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reprocess-no-lane/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reprocess-no-lane">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reprocess-no-lane/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/resolve-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/resolve-url">> = Specific
  const handler = {} as typeof import("../../app/api/admin/resolve-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/dogrulama-tekrar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/dogrulama-tekrar">> = Specific
  const handler = {} as typeof import("../../app/api/auth/dogrulama-tekrar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/giris/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/giris">> = Specific
  const handler = {} as typeof import("../../app/api/auth/giris/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/log">> = Specific
  const handler = {} as typeof import("../../app/api/auth/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/merge">> = Specific
  const handler = {} as typeof import("../../app/api/auth/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/switch-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/switch-account">> = Specific
  const handler = {} as typeof import("../../app/api/auth/switch-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/tekil-kontrol/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/tekil-kontrol">> = Specific
  const handler = {} as typeof import("../../app/api/auth/tekil-kontrol/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/excel-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/excel-import">> = Specific
  const handler = {} as typeof import("../../app/api/excel-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ilan/[id]/sahiplen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ilan/[id]/sahiplen">> = Specific
  const handler = {} as typeof import("../../app/api/ilan/[id]/sahiplen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ilan/[id]/telefon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ilan/[id]/telefon">> = Specific
  const handler = {} as typeof import("../../app/api/ilan/[id]/telefon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ilan/duzelt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ilan/duzelt">> = Specific
  const handler = {} as typeof import("../../app/api/ilan/duzelt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ilan/pasif/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ilan/pasif">> = Specific
  const handler = {} as typeof import("../../app/api/ilan/pasif/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ilan/sil/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ilan/sil">> = Specific
  const handler = {} as typeof import("../../app/api/ilan/sil/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ilanlar/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ilanlar/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/ilanlar/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/listings/ara/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listings/ara">> = Specific
  const handler = {} as typeof import("../../app/api/listings/ara/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/listings/yakin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listings/yakin">> = Specific
  const handler = {} as typeof import("../../app/api/listings/yakin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/llm-parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llm-parse">> = Specific
  const handler = {} as typeof import("../../app/api/llm-parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/moderator/arsiv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moderator/arsiv">> = Specific
  const handler = {} as typeof import("../../app/api/moderator/arsiv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/moderator/kullanici-askiya/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moderator/kullanici-askiya">> = Specific
  const handler = {} as typeof import("../../app/api/moderator/kullanici-askiya/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/moderator/toplu-islem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moderator/toplu-islem">> = Specific
  const handler = {} as typeof import("../../app/api/moderator/toplu-islem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/parse-text/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse-text">> = Specific
  const handler = {} as typeof import("../../app/api/parse-text/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/poi/[id]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/poi/[id]/review">> = Specific
  const handler = {} as typeof import("../../app/api/poi/[id]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/poi/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/poi/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/poi/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/poi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/poi">> = Specific
  const handler = {} as typeof import("../../app/api/poi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/raw-posts/telefon-doldur/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/raw-posts/telefon-doldur">> = Specific
  const handler = {} as typeof import("../../app/api/raw-posts/telefon-doldur/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/whatsapp-parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp-parse">> = Specific
  const handler = {} as typeof import("../../app/api/whatsapp-parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp">> = Specific
  const handler = {} as typeof import("../../app/api/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/devir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/devir">> = Specific
  const handler = {} as typeof import("../../app/auth/devir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cikis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/cikis">> = Specific
  const handler = {} as typeof import("../../app/cikis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/giris/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/giris">> = Specific
  const handler = {} as typeof import("../../app/giris/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/moderator-giris/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/moderator-giris">> = Specific
  const handler = {} as typeof import("../../app/moderator-giris/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profil-tamamla/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profil-tamamla">> = Specific
  const handler = {} as typeof import("../../app/profil-tamamla/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
