var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/excel-import/route.js")
R.c("server/chunks/lib_1q8466h._.js")
R.c("server/chunks/node_modules_1zp_q3c._.js")
R.c("server/chunks/[root-of-the-server]__0lm-hzr._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0u-n9p7._.js")
R.c("server/chunks/[root-of-the-server]__0xuaoik._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1pzhpk5.js")
R.c("server/chunks/lib_0htfl9m._.js")
R.c("server/chunks/_next-internal_server_app_api_excel-import_route_actions_1sxvzrt.js")
R.m(18850)
module.exports=R.m(18850).exports
