var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/radar/route.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1e8nxzq.js")
R.c("server/chunks/lib_0htfl9m._.js")
R.c("server/chunks/[root-of-the-server]__0lm-hzr._.js")
R.c("server/chunks/[root-of-the-server]__0xuaoik._.js")
R.c("server/chunks/node_modules_1zp_q3c._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0u-n9p7._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_radar_route_actions_067badk.js")
R.m(48170)
module.exports=R.m(48170).exports
