var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/link-havuzu/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04n94p6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0alesp5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_112o-1v.js")
R.c("server/chunks/ssr/node_modules_next_dist_0890nbp._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03x15pz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jlf4i0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/app_opengraph-image_alt_txt_mjs_1h9sou7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1af0ehu._.js")
R.c("server/chunks/ssr/node_modules_@supabase_supabase-js_dist_index_mjs_087pi7g._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_link-havuzu_page_actions_19jn_42.js")
R.m(18396)
module.exports=R.m(18396).exports
